AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A hello world application.
Resources:
  post:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/line-post
      Runtime: go1.x
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /line-post
            Method: post
      Environment:
        Variables:
          APP_ENV: local
