AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A hello world application.
Resources:
  slim:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/main
      Runtime: go1.x
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /slim
            Method: get
      Environment:
        Variables:
          APP_ENV: local
