@startuml
package Interactor #f9d423{
    interface DataBaseAccess
    component LoadGenerator
    component SlimLoadResponse<<DS>>#Green
    component SlimLoadRequest<<DS>>#Green
    interface SlimLoadRequester
    interface SlimLoadResponder
    interface DataBaseFactory #00dffc

    LoadGenerator -> DataBaseAccess
    LoadGenerator -up-> SlimLoadResponse
    LoadGenerator -up-> SlimLoadRequest
    LoadGenerator -up-> SlimLoadResponder
    SlimLoadRequester <|-- LoadGenerator

    package entity #ede574{
        component Load
    }
    DataBaseAccess -> Load
    DataBaseFactory ..> DataBaseAccess
}

package Controller　#fc913a{
    component SlimLoadController
    interface SlimLoadReceiver
    interface ReceiverFactory #00dffc

    SlimLoadController -left-> SlimLoadReceiver
    ReceiverFactory ..> SlimLoadReceiver
}
SlimLoadController -down-> SlimLoadRequest
SlimLoadController -right-> SlimLoadRequester

package DataBase#fc913a{
    component Repository
    interface FireBaseAccess
    component DatabaseFactoryImpl #2b90d9
    interface FireBaseFactory #00dffc

    Repository --> FireBaseAccess
    DatabaseFactoryImpl -> Repository
    FireBaseFactory ..> FireBaseAccess
}

package FireBase#ff4e50{
    component FireBaseSDK
    component FireBaseFactoryImpl #2b90d9
    FireBaseFactoryImpl -> FireBaseSDK
}

FireBaseSDK -up-|> FireBaseAccess

package HttpReceiver#ff4e50{
    component Receiver
    component ReceiverFactoryImpl #2b90d9

    ReceiverFactoryImpl -> Receiver
}

package Presenter#fc913a{
    component LinePresenter
    component LineModel<<DS>>#Green
    interface LineViewer
    interface ViewFactory #00dffc

    LinePresenter --> LineModel
    LineViewer --> LineModel
    LinePresenter --> LineViewer
    ViewFactory .> LineViewer
}

package View#ff4e50{
    Component LineView
    component ViewFactoryImpl #2b90d9

    ViewFactoryImpl -> LineView
}

node line#Red
database firebase#Red
FireBaseSDK -> firebase
LineViewer <|-- LineView
LineView --> line
SlimLoadResponder <|-up- LinePresenter
SlimLoadResponse <-- LinePresenter
DataBaseAccess <|-down- Repository
Receiver --|> SlimLoadReceiver

DataBaseFactory <|-- DatabaseFactoryImpl
FireBaseFactory <|-- FireBaseFactoryImpl
ViewFactory <|-- ViewFactoryImpl
ReceiverFactoryImpl --|> ReceiverFactory

@enduml
