@startuml
package Interactor #f9d423{
    interface DataBaseAccessor
    component LoadGenerator
    component SlimLoadResponse<<DS>>#Green
    component SlimLoadRequest<<DS>>#Green
    interface SlimLoadRequester
    interface SlimLoadResponder

    LoadGenerator -right-> DataBaseAccessor
    LoadGenerator -up-> SlimLoadResponse
    LoadGenerator -up-> SlimLoadRequest
    LoadGenerator -up-> SlimLoadResponder
    SlimLoadRequester <|-down- LoadGenerator

    package entity #ede574{
        component Load
    }
    DataBaseAccessor -right-> Load
}

package Controller　#fc913a{
    component SlimLoadController
    interface Receiver
    Receiver <-left- SlimLoadController
}

package DataBase#fc913a{
    component Repository
    interface FireBaseAccess

    Repository -down-> FireBaseAccess
}

package FireBase#ff4e50{
    component FireBaseSDK
}

package Presenter#fc913a{
    package web {
        component WebModel #Green
        component WebPresenter
        WebPresenter -down-> WebModel
        interface WebViewer
        WebViewer -down-> WebModel
        WebPresenter -right-> WebViewer
    }

    package line {
        component LineModel #Green
        component LinePresenter
        LinePresenter -down-> LineModel
        interface LineViewer
        LineViewer -down-> LineModel
        LinePresenter -right-> LineViewer
    }
}

package LineView #ff4e50 {
    component lineview
}

package WebbView #ff4e50 {
    component webview
}

package Lambda #ff4e50 {
   component Handle

}

' Controller => Interactor
SlimLoadController -down-> SlimLoadRequest
SlimLoadController -down-> SlimLoadRequester

' Presenter => Interactor
LinePresenter -down-|> SlimLoadResponder
WebPresenter -down-|> SlimLoadResponder


' DataBase => Interactor
Repository -up-|> DataBaseAccessor

' Lambda => Presenter/Controller
Handle -down-|> Receiver

' FireBase => DataBase
FireBaseSDK -up-|> FireBaseAccess

' Presenter => View
lineview -down-|> LineViewer
webview -down-|> WebViewer

@enduml
